### ISSUE TITLE
Using MAC-SQL for a specific databse

### ISSUE THREAD

**Issue by EnricDataS** [wbbeyourself/MAC-SQL#13]
Hello everybody,

I am working with a group of students in a text-to-SQL tool for a specific database, and given your amazing work and results we decided to try to use your framework. Our idea is to generate a question-query dataset from the single database (which contains about a 1000 tables) to use it with your framework. In our case, we only have available (for the moment) GPT-3.5 Turbo but, since the queries to make are in principle very simple (not even with JOINS), we believe it would be good enough for us. Also, we are working on creating table embeddings (using the table descriptions in natural language) as a selection method, so the selector agent could be omitted in case this accelerates the process.

We would appreciate some basic guidelines and/or corrections/advice on our approach.

Thank you for your great job!

**Comment by wbbeyourself** [comment]
Thank you for your interest in our work, and I think your idea is great. Based on your description, it is indeed possible to customize a table filtering method that suits your needs, without using the Selector mentioned in the paper, because our framework is designed to allow flexible replacement for each agent.

In addition, you mentioned using GPT-3.5-turbo, which is also entirely feasible, as the SQL query you need to generate is relatively simple.
