### ISSUE TITLE
Decomposition on Spider

### ISSUE THREAD

**Issue by hoangdzung** [wbbeyourself/MAC-SQL#8]
Thank you so much for your great work.
I notice that the `decompose_template_spider` is just one-shot without any form of decomposition like `decompose_template_bird`. Is there any reason for you to do that? Probably spider is way more simpler than bird?
Thank you so much for your help.

**Comment by wbbeyourself** [comment]
Yes, we find that using complex decomposition method for Spider will decrease the performace. Because Spider dataset tends to generate more straitforward join SQL instead of nested SQL in BIRD. Using template like `decompose_template_bird`  in Spider will lead to nested SQL results, which  degrades the EX accuracy in Spider.

**Comment by hoangdzung** [comment]
Thank you so much for your prompt response!
